export const EDITORIAL_TEXTS = [
  {
    key: 'Home.TaglinePrefix',
    group: 'Home',
    fr: "Le FISD, c'est",
    en: 'FISD is',
  },
  {
    key: 'Home.HeroReserve',
    group: 'Home',
    fr: 'Réserver une place',
    en: 'Reserve a spot',
  },
  {
    key: 'Home.HeroDiscover',
    group: 'Home',
    fr: 'Découvrir le FISD',
    en: 'Discover FISD',
  },
  {
    key: 'Home.HeroPastEditions',
    group: 'Home',
    fr: 'Voir le programme',
    en: 'View the programme',
  },
  {
    key: 'Home.CountdownTitle',
    group: 'Home',
    fr: 'Compte à rebours avant le FISD 2026',
    en: 'Countdown to FISD 2026',
  },
  {
    key: 'Home.StatsEyebrow',
    group: 'Home',
    fr: 'Le FISD en chiffres',
    en: 'FISD by the numbers',
  },
  {
    key: 'Home.StatsTitle',
    group: 'Home',
    fr: 'Le FISD en chiffres',
    en: 'FISD in figures',
  },
  {
    key: 'Home.StatsEditions',
    group: 'Home',
    fr: 'Éditions organisées',
    en: 'Editions held',
  },
  {
    key: 'Home.StatsSpeakers',
    group: 'Home',
    fr: 'Intervenants et panélistes',
    en: 'Speakers and panelists',
  },
  {
    key: 'Home.PresentationEyebrow',
    group: 'Home',
    fr: 'Thème principal du FISD 2026',
    en: 'FISD 2026 main theme',
  },
  {
    key: 'Home.PresentationTitle',
    group: 'Home',
    fr: 'Formation, entrepreneuriat et coopération économique : les diasporas, alliées d’ici et de là-bas',
    en: 'Training, entrepreneurship and economic cooperation: diasporas, allies here and abroad',
  },
  {
    key: 'Home.PresentationParagraph1',
    group: 'Home',
    fr: '2025 : une rupture historique dans le financement du développement. Plusieurs indicateurs témoignent d’un recul considérable de l’aide publique au développement. Cette contraction budgétaire intervient à un moment charnière, alors que des défis majeurs — le chômage des jeunes, l’essor de l’intelligence artificielle, la transition écologique et la sécurité alimentaire — exigent de nouveaux mécanismes de collaboration fondés sur l’innovation, le partage de compétences et les investissements stratégiques.',
    en: '2025: a historic shift in development financing. Several indicators point to a significant decline in official development assistance. This contraction comes at a pivotal time, as youth unemployment, the rise of artificial intelligence, the ecological transition and food security call for new forms of collaboration based on innovation, knowledge sharing and strategic investment.',
  },
  {
    key: 'Home.PresentationParagraph2',
    group: 'Home',
    fr: 'Le recul de l’aide publique au développement, la montée en puissance d’une diaspora de plus en plus qualifiée et entrepreneure, ainsi que la nécessité de bâtir une coopération internationale fondée sur des partenariats Nord-Sud plus équitables, valorisant les expertises locales, justifient le thème retenu pour la 3ᵉ édition du FISD.',
    en: 'Declining development assistance, increasingly skilled and entrepreneurial diasporas, and the need for more equitable North–South partnerships that value local expertise underpin the theme of the third FISD edition.',
  },
  {
    key: 'Home.PresentationParagraph3',
    group: 'Home',
    fr: 'Le FISD dépasse la logique d’un événement ponctuel : il s’agit d’un écosystème permanent, avec des mécanismes de suivi des activités post-forum et des ressources d’accompagnement.',
    en: 'FISD goes beyond a one-off event: it is a lasting ecosystem with follow-up mechanisms for post-forum activities and resources to support participants.',
  },
  {
    key: 'Home.PresentationMoreLabel',
    group: 'Home',
    fr: 'En savoir plus',
    en: 'Learn more',
  },
  {
    key: 'Home.PresentationLessLabel',
    group: 'Home',
    fr: 'Voir moins',
    en: 'Show less',
  },
  {
    key: 'Home.PanelTitle',
    group: 'Home',
    fr: 'Retombées, impacts et suivi post-forum',
    en: 'Outcomes, impact and follow-up',
  },
  {
    key: 'Home.PanelText',
    group: 'Home',
    fr: 'Un écosystème permanent pour accompagner les initiatives et prolonger les collaborations au-delà du forum.',
    en: 'A lasting ecosystem to support initiatives and extend collaboration beyond the forum.',
  },
  {
    key: 'Home.PanelTag',
    group: 'Home',
    fr: 'Des collaborations durables',
    en: 'Lasting collaboration',
  },
  {
    key: 'Home.PillarsEyebrow',
    group: 'Home',
    fr: 'Notre raison d’être',
    en: 'Our purpose',
  },
  {
    key: 'Home.PillarsTitle',
    group: 'Home',
    fr: 'Le FISD est…',
    en: 'FISD is…',
  },
  {
    key: 'Home.SpeakersEyebrow',
    group: 'Home',
    fr: 'Quelques personnalités',
    en: 'Featured guests',
  },
  {
    key: 'Home.SpeakersTitle',
    group: 'Home',
    fr: 'Les intervenants du FISD 2026',
    en: 'FISD 2026 speakers',
  },
  {
    key: 'Home.SpeakersDescription',
    group: 'Home',
    fr: "Les intervenants de l'édition 2026 seront annoncés prochainement.",
    en: "The 2026 edition's speakers will be announced soon.",
  },
  {
    key: 'Home.PartnersEyebrow',
    group: 'Home',
    fr: 'Ils participent au forum',
    en: 'Taking part in the forum',
  },
  {
    key: 'Home.PartnersTitle',
    group: 'Home',
    fr: 'Partenaires et exposants',
    en: 'Partners and exhibitors',
  },
  {
    key: 'Home.PillarsIntro',
    group: 'Home',
    fr: 'Le lancement du FISD en 2024 fait suite à un constat partagé : l’existence d’un déficit d’espaces structurés et inclusifs de concertation et de connexion entre les diasporas, les acteurs du développement international, les pouvoirs publics, les communautés locales et les responsables territoriaux décentralisés. Le FISD contribue à une coopération plus horizontale et plus équitable en créant progressivement une communauté d’acteurs engagés.',
    en: 'Launched in 2024, FISD responds to a shared observation: a lack of structured, inclusive spaces connecting diasporas, international development actors, public authorities, local communities and decentralised territorial leaders. FISD builds a community of committed actors working towards more equitable, horizontal cooperation.',
  },
  {
    key: 'Home.Pillar1',
    group: 'Home',
    fr: 'L’implication des diasporas',
    en: 'Diaspora involvement',
  },
  {
    key: 'Home.Pillar2',
    group: 'Home',
    fr: 'L’entrepreneuriat social et la coopération décentralisée',
    en: 'Social entrepreneurship and decentralised cooperation',
  },
  {
    key: 'Home.Pillar3',
    group: 'Home',
    fr: 'La reconnaissance des savoirs et des expertises locales',
    en: 'Recognising local knowledge and expertise',
  },
  {
    key: 'Home.ProgramTitle',
    group: 'Home',
    fr: 'Programme',
    en: 'Programme',
  },
  {
    key: 'Home.ProgramIntro',
    group: 'Home',
    fr: 'Préparez-vous à trois jours d’immersion stratégique et transformative, suivis d’activités post-forum exclusives, conçues pour maximiser les retombées concrètes de votre participation.',
    en: 'Get ready for three days of strategic, transformative immersion, followed by exclusive post-forum activities designed to maximise the tangible outcomes of your participation.',
  },
  {
    key: 'Home.ProgramDay',
    group: 'Home',
    fr: 'Jour',
    en: 'Day',
  },
  {
    key: 'Home.ProgramDay1',
    group: 'Home',
    fr: 'Visibilité, bonnes pratiques et action',
    en: 'Visibility, good practices and action',
  },
  {
    key: 'Home.ProgramDay2',
    group: 'Home',
    fr: 'Partage d’expériences et synergies d’action',
    en: 'Sharing experiences and building synergies',
  },
  {
    key: 'Home.ProgramDay3',
    group: 'Home',
    fr: 'Rencontres B&B, visite de terrain et cérémonie de clôture',
    en: 'B&B meetings, field visit and closing ceremony',
  },
  {
    key: 'Home.ProgramButton',
    group: 'Home',
    fr: 'Voir le programme en détail',
    en: 'View the full programme',
  },
  {
    key: 'Nav.SwitchLanguage',
    group: 'Nav',
    fr: 'Changer de langue',
    en: 'Switch language',
  },
  {
    key: 'Nav.Home',
    group: 'Nav',
    fr: 'Accueil',
    en: 'Home',
  },
  {
    key: 'Nav.About',
    group: 'Nav',
    fr: 'À propos',
    en: 'About',
  },
  {
    key: 'Nav.AboutPresentation',
    group: 'Nav',
    fr: 'Thème principal',
    en: 'Main theme',
  },
  {
    key: 'Nav.AboutObjectives',
    group: 'Nav',
    fr: 'Le FISD est…',
    en: 'FISD is…',
  },
  {
    key: 'Nav.Engage',
    group: 'Nav',
    fr: 'Agir avec nous',
    en: 'Get involved',
  },
  {
    key: 'Nav.EngagePartner',
    group: 'Nav',
    fr: 'Devenir partenaire',
    en: 'Become a partner',
  },
  {
    key: 'Nav.EngageStand',
    group: 'Nav',
    fr: 'Prendre un stand',
    en: 'Book a booth',
  },
  {
    key: 'Nav.EngageVolunteer',
    group: 'Nav',
    fr: 'Devenir bénévole',
    en: 'Become a volunteer',
  },
  {
    key: 'Nav.EngageDonate',
    group: 'Nav',
    fr: 'Faire un don',
    en: 'Donate',
  },
  {
    key: 'Nav.Programming',
    group: 'Nav',
    fr: 'Programme du forum',
    en: 'Forum programme',
  },
  {
    key: 'Nav.PreviousEdition',
    group: 'Nav',
    fr: 'Éditions précédentes',
    en: 'Previous editions',
  },
  {
    key: 'Nav.News',
    group: 'Nav',
    fr: 'Actualités',
    en: 'News',
  },
  {
    key: 'Nav.Contact',
    group: 'Nav',
    fr: 'Contacts',
    en: 'Contact',
  },
  {
    key: 'Nav.Reserve',
    group: 'Nav',
    fr: 'Réserver ma place',
    en: 'Reserve my spot',
  },
  {
    key: 'Nav.Administration',
    group: 'Nav',
    fr: 'Administration',
    en: 'Administration',
  },
  {
    key: 'Nav.OpenMenu',
    group: 'Nav',
    fr: 'Ouvrir le menu',
    en: 'Open menu',
  },
  {
    key: 'Nav.Report',
    group: 'Nav',
    fr: 'Rapport synthèse',
    en: 'Summary report',
  },
  {
    key: 'Footer.Tagline',
    group: 'Footer',
    fr: "Connecter les acteurs d'ici et d'ailleurs.",
    en: 'Connecting actors from here and abroad.',
  },
  {
    key: 'Footer.About',
    group: 'Footer',
    fr: 'À propos',
    en: 'About',
  },
  {
    key: 'Footer.Menu',
    group: 'Footer',
    fr: 'Menu',
    en: 'Menu',
  },
  {
    key: 'Footer.Conditions',
    group: 'Footer',
    fr: 'Conditions générales',
    en: 'Terms and conditions',
  },
  {
    key: 'Footer.ContactsTitle',
    group: 'Footer',
    fr: 'Contacts',
    en: 'Contact',
  },
  {
    key: 'Footer.Copyright',
    group: 'Footer',
    fr: 'Jeunes Solidaires © {{year}}. Tous droits réservés.',
    en: 'Jeunes Solidaires © {{year}}. All rights reserved.',
  },
  {
    key: 'Footer.Newsletter',
    group: 'Footer',
    fr: 'S’abonner à l’infolettre',
    en: 'Subscribe to the newsletter',
  },
  {
    key: 'Footer.NewsletterText',
    group: 'Footer',
    fr: 'Recevez les nouvelles du forum et les prochaines occasions de participer.',
    en: 'Receive forum news and upcoming opportunities to take part.',
  },
  {
    key: 'Footer.NewsletterPending',
    group: 'Footer',
    fr: 'Les modalités d’inscription seront annoncées prochainement.',
    en: 'Subscription details will be announced soon.',
  },
  {
    key: 'Footer.Facebook',
    group: 'Footer',
    fr: 'Retrouvez le FISD sur Facebook',
    en: 'Find FISD on Facebook',
  },
  {
    key: 'Footer.FacebookLoad',
    group: 'Footer',
    fr: 'Afficher les publications Facebook',
    en: 'Show Facebook posts',
  },
  {
    key: 'Footer.FacebookPrivacy',
    group: 'Footer',
    fr: 'L’affichage des publications charge du contenu fourni par Facebook.',
    en: 'Showing posts loads content provided by Facebook.',
  },
  {
    key: 'Programming.HeroEyebrow',
    group: 'Programming',
    fr: 'Programmation',
    en: 'Programme',
  },
  {
    key: 'Programming.HeroTitle',
    group: 'Programming',
    fr: 'Programme du forum',
    en: 'Forum programme',
  },
  {
    key: 'Programming.HeroDescription',
    group: 'Programming',
    fr: 'Trois journées pour se rencontrer, partager et agir ensemble.',
    en: 'Three days to meet, share and act together.',
  },
  {
    key: 'Programming.SectionEyebrow',
    group: 'Programming',
    fr: 'Programme du forum',
    en: 'Forum programme',
  },
  {
    key: 'Programming.SectionTitle',
    group: 'Programming',
    fr: 'Édition 2026',
    en: '2026 edition',
  },
  {
    key: 'Programming.ActivitiesCount',
    group: 'Programming',
    fr: '{{count}} activités',
    en: '{{count}} activities',
  },
  {
    key: 'Programming.Location',
    group: 'Programming',
    fr: 'Lieu',
    en: 'Location',
  },
  {
    key: 'Gallery.HeroEyebrow',
    group: 'Gallery',
    fr: 'Éditions précédentes',
    en: 'Previous editions',
  },
  {
    key: 'Gallery.HeroTitle',
    group: 'Gallery',
    fr: 'Éditions précédentes',
    en: 'Previous editions',
  },
  {
    key: 'Gallery.HeroDescription',
    group: 'Gallery',
    fr: 'Sélectionnez une édition, puis parcourez les photos associées pour revivre les moments forts du forum.',
    en: "Pick an edition, then browse its photos to relive the forum's highlights.",
  },
  {
    key: 'Gallery.SectionEyebrow',
    group: 'Gallery',
    fr: 'Souvenirs des éditions précédentes',
    en: 'Memories from past editions',
  },
  {
    key: 'Gallery.SectionTitle',
    group: 'Gallery',
    fr: 'Une galerie organisée par édition',
    en: 'A gallery organized by edition',
  },
  {
    key: 'Gallery.SectionDescription',
    group: 'Gallery',
    fr: 'Chaque édition peut contenir plusieurs photos et témoignages.',
    en: 'Each edition can hold several photos and testimonials.',
  },
  {
    key: 'Gallery.ArchivedProgram',
    group: 'Gallery',
    fr: "Consulter le programme de l'édition {{edition}}",
    en: "See the {{edition}} edition's programme",
  },
  {
    key: 'Gallery.DefaultUpcomingTitle',
    group: 'Gallery',
    fr: 'À venir',
    en: 'Coming soon',
  },
  {
    key: 'Gallery.DefaultUpcomingText',
    group: 'Gallery',
    fr: "Les souvenirs de cette édition seront publiés ici dès qu'ils seront disponibles.",
    en: 'Memories from this edition will be published here once available.',
  },
  {
    key: 'Gallery.TestimonialsEyebrow',
    group: 'Gallery',
    fr: 'Témoignages',
    en: 'Testimonials',
  },
  {
    key: 'Gallery.TestimonialsTitle',
    group: 'Gallery',
    fr: 'Ce que disent les participants du FISD',
    en: 'What FISD participants are saying',
  },
  {
    key: 'Gallery.TestimonialLabel',
    group: 'Gallery',
    fr: 'Témoignage',
    en: 'Testimonial',
  },
  {
    key: 'News.HeroEyebrow',
    group: 'News',
    fr: 'Publications',
    en: 'Publications',
  },
  {
    key: 'News.HeroTitle',
    group: 'News',
    fr: 'Actualités',
    en: 'News',
  },
  {
    key: 'News.HeroDescription',
    group: 'News',
    fr: 'Retrouvez les articles, infolettres, communiqués et nouvelles du Forum.',
    en: "Find the Forum's articles, newsletters, press releases and news.",
  },
  {
    key: 'News.SectionEyebrow',
    group: 'News',
    fr: 'Publications',
    en: 'Publications',
  },
  {
    key: 'News.SectionTitle',
    group: 'News',
    fr: 'Publications du FISD',
    en: 'FISD publications',
  },
  {
    key: 'News.SectionDescription',
    group: 'News',
    fr: 'Les contenus publiés sont regroupés ici pour garder une trace claire de la vie du forum.',
    en: "Published content is gathered here to keep a clear record of the forum's life.",
  },
  {
    key: 'News.EmptyTitle',
    group: 'News',
    fr: 'Aucune publication pour le moment',
    en: 'No publications yet',
  },
  {
    key: 'News.Published',
    group: 'News',
    fr: 'Publié',
    en: 'Published',
  },
  {
    key: 'Contact.HeroEyebrow',
    group: 'Contact',
    fr: 'Contacts',
    en: 'Contact',
  },
  {
    key: 'Contact.HeroTitle',
    group: 'Contact',
    fr: "Contacter l'équipe du FISD",
    en: 'Contact the FISD team',
  },
  {
    key: 'Contact.HeroDescription',
    group: 'Contact',
    fr: 'Téléphone, WhatsApp ou courriel : choisissez le canal le plus simple pour vos questions, partenariats et informations pratiques.',
    en: 'Phone, WhatsApp or email: pick whichever channel is easiest for your questions, partnerships and practical information.',
  },
  {
    key: 'Contact.FormTitle',
    group: 'Contact',
    fr: 'Écrivez-nous',
    en: 'Write to us',
  },
  {
    key: 'Contact.FieldName',
    group: 'Contact',
    fr: 'Nom complet',
    en: 'Full name',
  },
  {
    key: 'Contact.FieldEmail',
    group: 'Contact',
    fr: 'Adresse e-mail',
    en: 'Email address',
  },
  {
    key: 'Contact.FieldMessage',
    group: 'Contact',
    fr: 'Message',
    en: 'Message',
  },
  {
    key: 'Contact.Submit',
    group: 'Contact',
    fr: 'Envoyer un courriel',
    en: 'Send an email',
  },
  {
    key: 'Contact.CtaPhone',
    group: 'Contact',
    fr: 'Appeler',
    en: 'Call',
  },
  {
    key: 'Contact.CtaWhatsApp',
    group: 'Contact',
    fr: 'Ouvrir WhatsApp',
    en: 'Open WhatsApp',
  },
  {
    key: 'Contact.CtaEmail',
    group: 'Contact',
    fr: 'Envoyer un courriel',
    en: 'Send an email',
  },
  {
    key: 'Contact.CtaGeneric',
    group: 'Contact',
    fr: 'Nous joindre',
    en: 'Reach us',
  },
  {
    key: 'Contact.PhoneAndWhatsApp',
    group: 'Contact',
    fr: 'Téléphone et WhatsApp',
    en: 'Phone and WhatsApp',
  },
  {
    key: 'Engagement.HeroEyebrow',
    group: 'Engagement',
    fr: 'Agir avec nous',
    en: 'Get involved',
  },
  {
    key: 'Engagement.HeroTitle',
    group: 'Engagement',
    fr: 'Passez de visiteur à acteur engagé du FISD',
    en: 'Go from visitor to active FISD contributor',
  },
  {
    key: 'Engagement.HeroDescription',
    group: 'Engagement',
    fr: 'Cette page regroupe les différentes façons de participer activement au forum.',
    en: 'This page gathers the different ways to take an active part in the forum.',
  },
  {
    key: 'Engagement.IntroEyebrow',
    group: 'Engagement',
    fr: "N'hésitez plus !",
    en: "Don't wait!",
  },
  {
    key: 'Engagement.IntroTitle',
    group: 'Engagement',
    fr: 'Choisissez la bonne façon de participer au Forum International Solidarité et Développement',
    en: 'Choose the right way to take part in the International Forum for Solidarity and Development',
  },
  {
    key: 'Engagement.IntroText',
    group: 'Engagement',
    fr: "Partenariat, stand ou bénévolat : chaque parcours dispose maintenant de son formulaire dédié pour simplifier le suivi avec l'équipe du FISD.",
    en: 'Partnership, booth, or volunteering: each path now has its own dedicated form to make follow-up with the FISD team easier.',
  },
  {
    key: 'Engagement.HighlightPartners',
    group: 'Engagement',
    fr: 'Partenaires',
    en: 'Partners',
  },
  {
    key: 'Engagement.HighlightExhibitors',
    group: 'Engagement',
    fr: 'Exposants',
    en: 'Exhibitors',
  },
  {
    key: 'Engagement.HighlightVolunteers',
    group: 'Engagement',
    fr: 'Bénévoles',
    en: 'Volunteers',
  },
  {
    key: 'Engagement.ActionsEyebrow',
    group: 'Engagement',
    fr: "S'impliquer",
    en: 'Get involved',
  },
  {
    key: 'Engagement.ActionsTitle',
    group: 'Engagement',
    fr: 'Trois parcours clairs pour agir avec nous',
    en: 'Three clear paths to take action with us',
  },
  {
    key: 'Engagement.ActionsDescription',
    group: 'Engagement',
    fr: "Choisissez l'option qui correspond à votre besoin. Le formulaire s'ouvrira dans un nouvel onglet.",
    en: 'Choose the option that fits your needs. The form will open in a new tab.',
  },
  {
    key: 'Engagement.GuideEyebrow',
    group: 'Engagement',
    fr: 'Comment ça marche',
    en: 'How it works',
  },
  {
    key: 'Engagement.GuideTitle',
    group: 'Engagement',
    fr: 'Un chemin simple, sans formulaire en double',
    en: 'A simple path, with no duplicate forms',
  },
  {
    key: 'Engagement.GuideText',
    group: 'Engagement',
    fr: 'Pour éviter les demandes perdues, chaque bouton renvoie directement au formulaire officiel correspondant.',
    en: 'To avoid lost requests, each button leads directly to the matching official form.',
  },
  {
    key: 'Engagement.Step1Title',
    group: 'Engagement',
    fr: 'Choisissez votre rôle',
    en: 'Choose your role',
  },
  {
    key: 'Engagement.Step1Text',
    group: 'Engagement',
    fr: 'Sélectionnez le formulaire qui correspond à votre participation.',
    en: "Select the form that matches how you'd like to take part.",
  },
  {
    key: 'Engagement.Step2Title',
    group: 'Engagement',
    fr: 'Remplissez le formulaire',
    en: 'Fill out the form',
  },
  {
    key: 'Engagement.Step2Text',
    group: 'Engagement',
    fr: "Les demandes arrivent directement à l'équipe du FISD.",
    en: 'Requests go straight to the FISD team.',
  },
  {
    key: 'Engagement.Step3Title',
    group: 'Engagement',
    fr: 'Notre équipe vous recontacte',
    en: 'Our team follows up',
  },
  {
    key: 'Engagement.Step3Text',
    group: 'Engagement',
    fr: 'Un suivi est fait pour confirmer les prochaines étapes.',
    en: 'We reach out to confirm the next steps.',
  },
  {
    key: 'Engagement.PartnersEyebrow',
    group: 'Engagement',
    fr: 'Nos partenaires',
    en: 'Our partners',
  },
  {
    key: 'Engagement.PartnersTitle',
    group: 'Engagement',
    fr: 'Ils accompagnent la dynamique du FISD',
    en: "They support FISD's momentum",
  },
  {
    key: 'Engagement.PartnersDescription',
    group: 'Engagement',
    fr: 'Retrouvez les institutions et organisations qui soutiennent la portée du forum.',
    en: "Meet the institutions and organizations backing the forum's reach.",
  },
  {
    key: 'Reservation.HeroEyebrow',
    group: 'Reservation',
    fr: 'Réserver une place',
    en: 'Reserve a spot',
  },
  {
    key: 'Reservation.HeroTitle',
    group: 'Reservation',
    fr: 'Acheter votre ticket',
    en: 'Get your ticket',
  },
  {
    key: 'Reservation.HeroDescription',
    group: 'Reservation',
    fr: 'Le nombre de personnes pouvant participer au Forum International Solidarité et Développement (FISD) étant limité, prenez action, inscrivez-vous.',
    en: 'Space at the International Forum for Solidarity and Development (FISD) is limited - take action and register.',
  },
  {
    key: 'Reservation.TicketingEyebrow',
    group: 'Reservation',
    fr: 'Billetterie FISD 2026',
    en: 'FISD 2026 ticketing',
  },
  {
    key: 'Reservation.TicketingTitle',
    group: 'Reservation',
    fr: 'Acheter votre ticket',
    en: 'Get your ticket',
  },
  {
    key: 'Reservation.NextEdition',
    group: 'Reservation',
    fr: 'Prochaine édition',
    en: 'Next edition',
  },
  {
    key: 'Reservation.NextEditionName',
    group: 'Reservation',
    fr: 'FISD 2026 - 26, 27 et 28 novembre 2026',
    en: 'FISD 2026 - November 26, 27 and 28, 2026',
  },
  {
    key: 'Reservation.NextEditionPlace',
    group: 'Reservation',
    fr: 'Lieu à confirmer',
    en: 'Location to be confirmed',
  },
  {
    key: 'Reservation.ZeffyLink',
    group: 'Reservation',
    fr: 'Lien de réservation Zeffy',
    en: 'Zeffy reservation link',
  },
  {
    key: 'Reservation.LimitedSeats',
    group: 'Reservation',
    fr: 'Le nombre de personnes pouvant participer au Forum International Solidarité et Développement (FISD) étant limité, prenez action, inscrivez-vous.',
    en: 'Space at the International Forum for Solidarity and Development (FISD) is limited - take action and register.',
  },
  {
    key: 'Reservation.TermsNoticePrefix',
    group: 'Reservation',
    fr: 'En poursuivant votre achat, vous reconnaissez avoir lu les',
    en: 'By continuing your purchase, you confirm you have read the',
  },
  {
    key: 'Reservation.TermsLinkLabel',
    group: 'Reservation',
    fr: 'conditions générales de participation',
    en: 'general terms of participation',
  },
  {
    key: 'Reservation.TermsCheckboxLabel',
    group: 'Reservation',
    fr: "J'ai lu et j'accepte les conditions d'utilisation",
    en: 'I have read and accept the terms of use',
  },
  {
    key: 'Reservation.ReserveCta',
    group: 'Reservation',
    fr: 'Réserver ma place',
    en: 'Reserve my spot',
  },
  {
    key: 'Reservation.ParticipationTitle',
    group: 'Reservation',
    fr: 'Participation au FISD',
    en: 'Taking part in FISD',
  },
  {
    key: 'Reservation.ParticipationText',
    group: 'Reservation',
    fr: 'Choisissez votre catégorie de participation avant de finaliser votre réservation.',
    en: 'Choose your participation category before finalizing your reservation.',
  },
  {
    key: 'Reservation.ParticipantTitle',
    group: 'Reservation',
    fr: 'Participant',
    en: 'Participant',
  },
  {
    key: 'Reservation.ParticipantText',
    group: 'Reservation',
    fr: 'Consultez les billets et choisissez votre formule de participation.',
    en: 'Check the tickets and choose your participation option.',
  },
  {
    key: 'Reservation.ParticipantCta',
    group: 'Reservation',
    fr: 'Consulter la billetterie',
    en: 'See ticketing',
  },
  {
    key: 'Reservation.GuestTitle',
    group: 'Reservation',
    fr: 'Invité',
    en: 'Guest',
  },
  {
    key: 'Reservation.GuestText',
    group: 'Reservation',
    fr: "Contactez l'équipe pour connaître les modalités associées à votre invitation.",
    en: 'Contact the team to learn about the terms tied to your invitation.',
  },
  {
    key: 'Reservation.GuestCta',
    group: 'Reservation',
    fr: "Contacter l'équipe",
    en: 'Contact the team',
  },
  {
    key: 'Conditions.HeroEyebrow',
    group: 'Conditions',
    fr: 'Conditions générales',
    en: 'Terms and conditions',
  },
  {
    key: 'Conditions.HeroTitle',
    group: 'Conditions',
    fr: 'Conditions générales de participation au FISD 2026',
    en: 'General terms of participation for FISD 2026',
  },
  {
    key: 'Conditions.HeroDescription',
    group: 'Conditions',
    fr: 'Veuillez lire attentivement les conditions de participation avant de réserver votre place.',
    en: 'Please read the terms of participation carefully before reserving your spot.',
  },
  {
    key: 'Conditions.Back',
    group: 'Conditions',
    fr: 'Retour à la réservation',
    en: 'Back to reservation',
  },
  {
    key: 'Conditions.PresentationTitle',
    group: 'Conditions',
    fr: 'Présentation',
    en: 'Overview',
  },
  {
    key: 'Conditions.PresentationP1',
    group: 'Conditions',
    fr: 'Le FISD (Forum International Solidarité et Développement) est un événement annuel organisé par Jeunes Solidaires Canada, une organisation à but non lucratif constituée en vertu de la Loi canadienne sur les organisations à but non lucratif.',
    en: 'FISD (International Forum for Solidarity and Development) is an annual event organized by Jeunes Solidaires Canada, a non-profit organization incorporated under the Canada Not-for-profit Corporations Act.',
  },
  {
    key: 'Conditions.PresentationP2',
    group: 'Conditions',
    fr: "Pour s'inscrire au forum, il est impératif pour tout participant de prendre connaissance et d'accepter les conditions de participation ainsi que les modalités d'inscription décrites ci-après. Le non-respect de ces conditions peut entraîner un refus de participation au Forum par l'organisateur.",
    en: 'To register for the forum, every participant must read and accept the terms of participation and the registration procedures described below. Failure to comply with these terms may lead the organizer to refuse participation in the Forum.',
  },
  {
    key: 'Conditions.EligibilityTitle',
    group: 'Conditions',
    fr: 'Admissibilité',
    en: 'Eligibility',
  },
  {
    key: 'Conditions.EligibilityIntro',
    group: 'Conditions',
    fr: 'Sont admissibles :',
    en: 'Eligible participants include:',
  },
  {
    key: 'Conditions.EligibilityItem1',
    group: 'Conditions',
    fr: 'Les personnes qui ont fait leur inscription en ligne et payé leur ticket de participation.',
    en: 'Those who registered online and paid for their participation ticket.',
  },
  {
    key: 'Conditions.EligibilityItem2',
    group: 'Conditions',
    fr: 'Les personnes invitées par le FISD (participants, panélistes, exposants, partenaires, etc.), qui résident au Canada ou ailleurs dans le monde et qui souhaitent proposer un sujet en lien avec le thème du Forum ou proposer un partenariat.',
    en: "Those invited by FISD (participants, panelists, exhibitors, partners, etc.), who reside in Canada or elsewhere in the world and wish to propose a topic related to the Forum's theme or propose a partnership.",
  },
  {
    key: 'Conditions.RegistrationTitle',
    group: 'Conditions',
    fr: "Méthode d'inscription en ligne",
    en: 'Online registration method',
  },
  {
    key: 'Conditions.RegistrationItem1',
    group: 'Conditions',
    fr: "Pour participer au Forum, il faut obligatoirement remplir le formulaire d'inscription en ligne sur le site officiel du FISD.",
    en: "To take part in the Forum, you must fill out the online registration form on FISD's official website.",
  },
  {
    key: 'Conditions.RegistrationItem2',
    group: 'Conditions',
    fr: 'Une fois le formulaire rempli, une notification est envoyée par e-mail confirmant que votre inscription a bien été prise en compte.',
    en: 'Once the form is submitted, an email notification confirms that your registration has been received.',
  },
  {
    key: 'Conditions.RegistrationItem3',
    group: 'Conditions',
    fr: "Une lettre d'invitation officielle de participation au forum vous sera transmise, incluant des directives sur l'organisation de l'événement.",
    en: "An official letter of invitation to the forum will be sent to you, including guidelines on the event's organization.",
  },
  {
    key: 'Conditions.RegistrationItem4',
    group: 'Conditions',
    fr: "Les frais d'inscription sont payés au moment de l'inscription en ligne, selon les modalités figurant sur le site web du FISD.",
    en: "Registration fees are paid at the time of online registration, according to the terms listed on FISD's website.",
  },
  {
    key: 'Conditions.RegistrationItem5',
    group: 'Conditions',
    fr: 'Le paiement se fait sur la plateforme de billetterie Zeffy.',
    en: 'Payment is made through the Zeffy ticketing platform.',
  },
  {
    key: 'Conditions.RegistrationItem6',
    group: 'Conditions',
    fr: 'Les modes de paiement autorisés sont : carte de débit, Visa, MasterCard, Amex, etc.',
    en: 'Accepted payment methods include: debit card, Visa, MasterCard, Amex, etc.',
  },
  {
    key: 'Conditions.PaymentIssuesPrefix',
    group: 'Conditions',
    fr: 'Si vous rencontrez des difficultés liées au paiement, écrivez-nous à',
    en: 'If you run into payment issues, write to us at',
  },
  {
    key: 'Conditions.PaymentIssuesOr',
    group: 'Conditions',
    fr: 'ou appelez-nous au',
    en: 'or call us at',
  },
  {
    key: 'Conditions.CancellationTitle',
    group: 'Conditions',
    fr: 'Annulation',
    en: 'Cancellation',
  },
  {
    key: 'Conditions.CancellationText',
    group: 'Conditions',
    fr: "Aucun remboursement ne sera effectué en cas d'annulation de votre inscription, peu importe les raisons. Néanmoins, en cas d'annulation, nous garantissons l'accès à certains contenus en ligne pendant et après le Forum.",
    en: 'No refund will be issued if you cancel your registration, regardless of the reason. That said, in the event of cancellation, we guarantee access to certain online content during and after the Forum.',
  },
  {
    key: 'Conditions.ClausesTitle',
    group: 'Conditions',
    fr: 'Clauses de participation',
    en: 'Participation clauses',
  },
  {
    key: 'Conditions.ParticipantsSubtitle',
    group: 'Conditions',
    fr: 'Participants',
    en: 'Participants',
  },
  {
    key: 'Conditions.ParticipantsItem1',
    group: 'Conditions',
    fr: 'Les participants doivent faire preuve de respect envers les autres participants, organisateurs, panélistes et exposants.',
    en: 'Participants must show respect toward other participants, organizers, panelists and exhibitors.',
  },
  {
    key: 'Conditions.ParticipantsItem2',
    group: 'Conditions',
    fr: "Les comportements inappropriés (harcèlement, sexisme, discrimination, racisme, violence physique, etc.) sont interdits. L'organisateur peut exclure un participant du forum sans remboursement en cas d'un tel comportement.",
    en: 'Inappropriate behaviour (harassment, sexism, discrimination, racism, physical violence, etc.) is prohibited. The organizer may exclude a participant from the forum without a refund in the event of such behaviour.',
  },
  {
    key: 'Conditions.ParticipantsItem3',
    group: 'Conditions',
    fr: 'Les participants doivent se soumettre aux conditions de sécurité mises en place sur le lieu du forum.',
    en: "Participants must comply with the safety measures put in place at the forum's venue.",
  },
  {
    key: 'Conditions.PanelistsSubtitle',
    group: 'Conditions',
    fr: 'Panélistes',
    en: 'Panelists',
  },
  {
    key: 'Conditions.PanelistsItem1',
    group: 'Conditions',
    fr: "Les panélistes doivent soumettre leurs propositions d'intervention via le site web du forum.",
    en: "Panelists must submit their speaking proposals through the forum's website.",
  },
  {
    key: 'Conditions.PanelistsItem2',
    group: 'Conditions',
    fr: 'Seuls les panélistes dont les propositions ont été retenues seront contactés.',
    en: 'Only panelists whose proposals are accepted will be contacted.',
  },
  {
    key: 'Conditions.PanelistsItem3',
    group: 'Conditions',
    fr: "L'organisateur communiquera avec les panélistes retenus au sujet de la stratégie de déroulement du panel.",
    en: "The organizer will get in touch with accepted panelists regarding the panel's format.",
  },
  {
    key: 'Conditions.PanelistsItem4',
    group: 'Conditions',
    fr: "En cas de désistement, les panélistes doivent informer l'organisateur afin que celui-ci puisse prendre les mesures nécessaires.",
    en: 'In the event of withdrawal, panelists must inform the organizer so that the necessary steps can be taken.',
  },
  {
    key: 'Conditions.PartnersSubtitle',
    group: 'Conditions',
    fr: 'Partenaires',
    en: 'Partners',
  },
  {
    key: 'Conditions.PartnersItem1',
    group: 'Conditions',
    fr: "Les partenaires doivent s'engager à participer au Forum en tant que sponsors ou exposants.",
    en: 'Partners must commit to taking part in the Forum as sponsors or exhibitors.',
  },
  {
    key: 'Conditions.PartnersItem2',
    group: 'Conditions',
    fr: "Toute autre initiative doit faire l'objet d'une discussion préalable avec le président du comité organisateur et obtenir son approbation.",
    en: "Any other initiative must be discussed in advance with the organizing committee's chair and receive their approval.",
  },
  {
    key: 'Conditions.PartnersItem3',
    group: 'Conditions',
    fr: "Un contrat relatif aux conditions de participation sera établi entre les partenaires et l'organisateur du Forum.",
    en: "A contract covering the terms of participation will be established between the partners and the Forum's organizer.",
  },
  {
    key: 'Conditions.PartnersItem4',
    group: 'Conditions',
    fr: 'Les deux parties devront respecter les engagements stipulés dans le contrat.',
    en: 'Both parties must honour the commitments set out in the contract.',
  },
  {
    key: 'Conditions.ForeignTitle',
    group: 'Conditions',
    fr: "Participants venant de l'étranger",
    en: 'Participants coming from abroad',
  },
  {
    key: 'Conditions.ForeignText',
    group: 'Conditions',
    fr: "Les personnes qui résident en dehors du Canada et qui souhaitent prendre part au forum doivent prendre en charge tous les frais liés à leur déplacement vers le Canada : démarches de visa, billet d'avion, hôtel, restauration, etc.",
    en: 'Those who reside outside Canada and wish to take part in the forum must cover all costs related to travelling to Canada: visa procedures, plane ticket, hotel, meals, etc.',
  },
  {
    key: 'Conditions.VisaTitle',
    group: 'Conditions',
    fr: 'Visa, hébergement et restauration',
    en: 'Visa, accommodation and meals',
  },
  {
    key: 'Conditions.VisaP1',
    group: 'Conditions',
    fr: "Nous prenons en charge la restauration de tous les participants inscrits pour la journée du 26 novembre ainsi que ceux inscrits pour les journées du 27 et 28 novembre 2026. Toutefois, la restauration en dehors de ces périodes, l'hébergement et les démarches de visa restent sous la responsabilité de chaque participant.",
    en: "We cover meals for all participants registered for November 26, as well as those registered for November 27 and 28, 2026. However, meals outside these periods, accommodation, and visa procedures remain each participant's responsibility.",
  },
  {
    key: 'Conditions.VisaP2',
    group: 'Conditions',
    fr: "Lorsque votre inscription est complétée, nous vous transmettrons une lettre de confirmation d'inscription au FISD ainsi qu'une copie de la facture relative au paiement des frais d'inscription afin de vous permettre d'entamer les démarches pour l'obtention d'un visa si nécessaire.",
    en: 'Once your registration is complete, we will send you a letter confirming your FISD registration along with a copy of the invoice for your registration fees, so you can begin the process of obtaining a visa if needed.',
  },
  {
    key: 'Conditions.VisaResourcePrefix',
    group: 'Conditions',
    fr: 'Ressource utile :',
    en: 'Useful resource:',
  },
  {
    key: 'Conditions.VisaResourceLinkLabel',
    group: 'Conditions',
    fr: 'Immigration, Réfugiés et Citoyenneté Canada (IRCC)',
    en: 'Immigration, Refugees and Citizenship Canada (IRCC)',
  },
  {
    key: 'Conditions.ImageRightsTitle',
    group: 'Conditions',
    fr: "Droit d'image",
    en: 'Image rights',
  },
  {
    key: 'Conditions.ImageRightsText',
    group: 'Conditions',
    fr: "En tant que participant ou panéliste au FISD, vous acceptez d'être photographié, filmé ou enregistré à des fins promotionnelles au compte de Jeunes Solidaires et du Forum International Solidarité et Développement (FISD).",
    en: 'As a FISD participant or panelist, you agree to be photographed, filmed or recorded for promotional purposes on behalf of Jeunes Solidaires and the International Forum for Solidarity and Development (FISD).',
  },
  {
    key: 'Report.Title',
    group: 'Report',
    fr: 'Rapport synthèse',
    en: 'Summary report',
  },
  {
    key: 'Report.Description',
    group: 'Report',
    fr: 'Retrouvez les enseignements et les retombées des éditions du FISD.',
    en: 'Explore the lessons and outcomes of FISD editions.',
  },
  {
    key: 'Report.Empty',
    group: 'Report',
    fr: 'Le rapport synthèse sera disponible ici après sa publication.',
    en: 'The summary report will be available here once published.',
  },
  {
    key: 'Report.Download',
    group: 'Report',
    fr: 'Consulter le rapport synthèse',
    en: 'Read the summary report',
  },
  {
    key: 'NewsDetail.Back',
    group: 'NewsDetail',
    fr: 'Retour aux publications',
    en: 'Back to publications',
  },
  {
    key: 'NewsDetail.NotFoundTitle',
    group: 'NewsDetail',
    fr: 'Cette publication est introuvable',
    en: 'This publication could not be found',
  },
];
