using System.Text;
using Fido2NetLib;
using Fisd.Api.Infrastructure;
using Fisd.Application;
using Fisd.Application.Email;
using Fisd.Application.Security;
using Fisd.Application.Site;
using Fisd.Persistence;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using NLog.Web;

var builder = WebApplication.CreateBuilder(args);

builder.Logging.ClearProviders();
builder.Host.UseNLog();

builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<Fisd.Persistence.Common.ICurrentAdminAccessor, HttpContextCurrentAdminAccessor>();
builder.Services.AddScoped<Fisd.Application.Services.Interfaces.ICurrentLanguageAccessor, HttpContextCurrentLanguageAccessor>();
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "Fisd API", Version = "v1" });
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header
    });
    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" } },
            Array.Empty<string>()
        }
    });
});

var connectionString = builder.Configuration.GetConnectionString("FisdDB");
builder.Services.AddDbContext<FisdDbContext>(options =>
    options.UseSqlServer(connectionString, sql => sql.EnableRetryOnFailure()));

// NLog.config's Database target references ${var:connectionString} - set here rather than a
// connectionStrings-style block since appsettings.json is the single source of truth for it.
if (NLog.LogManager.Configuration != null)
{
    NLog.LogManager.Configuration.Variables["connectionString"] = connectionString ?? string.Empty;
}

builder.Services.Configure<JwtOptions>(builder.Configuration.GetSection("FisdAuth:Jwt"));
builder.Services.Configure<StorageOptions>(builder.Configuration.GetSection("Storage"));
builder.Services.Configure<EmailOptions>(builder.Configuration.GetSection("Email"));
builder.Services.Configure<SiteOptions>(builder.Configuration.GetSection("Site"));
builder.Services.AddMemoryCache();

var fido2Section = builder.Configuration.GetSection("Fido2");
if (!builder.Environment.IsDevelopment() &&
    (string.IsNullOrWhiteSpace(fido2Section["ServerDomain"]) || !fido2Section.GetSection("Origins").GetChildren().Any()))
{
    // Fido2NetLib fails deep inside credential creation/assertion with an opaque error when
    // ServerDomain/Origins are blank - this happens today if ASPNETCORE_ENVIRONMENT doesn't
    // resolve to a config file that sets them (appsettings.json's base values are empty on
    // purpose, only appsettings.Integration.json generated by the pipeline sets real values).
    // Fail loudly at startup instead of letting every passkey attempt 500 with no clear cause.
    throw new InvalidOperationException(
        "Fido2:ServerDomain and Fido2:Origins must be configured outside Development - passkeys cannot work without them.");
}
builder.Services.AddFido2(fido2Section);
builder.Services.AddFisdApplication();

var jwtOptions = builder.Configuration.GetSection("FisdAuth:Jwt").Get<JwtOptions>() ?? new JwtOptions();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtOptions.Key)),
            ValidateIssuer = true,
            ValidIssuer = jwtOptions.Issuer,
            ValidateAudience = true,
            ValidAudience = jwtOptions.Audience,
            ClockSkew = TimeSpan.FromMinutes(1)
        };
    });
builder.Services.AddAuthorization();

var corsOrigins = builder.Configuration.GetSection("Cors:Origins").Get<string[]>() ?? [];
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy => policy.WithOrigins(corsOrigins).AllowAnyHeader().AllowAnyMethod());
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<FisdDbContext>();
    db.Database.Migrate();
}

if (!app.Environment.IsProduction())
{
    app.UseSwagger();
    app.UseSwaggerUI(options => options.SwaggerEndpoint("/swagger/v1/swagger.json", "Fisd API v1"));
}

app.UseMiddleware<ErrorHandlingMiddleware>();
app.UseMiddleware<SecurityHeadersMiddleware>();

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
    app.UseHttpsRedirection();
}

var storageOptions = app.Services.GetRequiredService<Microsoft.Extensions.Options.IOptions<StorageOptions>>().Value;
var mediaRootPath = Path.IsPathRooted(storageOptions.MediaRootPath)
    ? storageOptions.MediaRootPath
    : Path.Combine(app.Environment.ContentRootPath, storageOptions.MediaRootPath);
Directory.CreateDirectory(mediaRootPath);
app.UseStaticFiles(new Microsoft.AspNetCore.Builder.StaticFileOptions
{
    FileProvider = new Microsoft.Extensions.FileProviders.PhysicalFileProvider(mediaRootPath),
    RequestPath = "/media"
});

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

try
{
    app.Run();
}
finally
{
    NLog.LogManager.Shutdown();
}

public partial class Program { }
